# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09d1fdf0a8006c85dac56228a15e5513ac8d9c3916415d66b9b9e9dc0429434b2b9d9d22f63e1521e179165a4dc02e926d19bb18056dbc9833e4670635711d43

test:
  secret_key_base: b12f4cf8a66056a6e05aa91b742d95cefd3c0a9c25833da1d5068d65d19a8d8b4b454d462d40c6437b0c6577488973aa09ff99c2797d7098452708de9346a869

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
